### ISSUE TITLE
Metatable

### ISSUE THREAD

**Issue by Positive07** [rm-code/deco#1]
You could change all the decorators file `return` value to something like
```lua
return setmetatable(decorator, {__call = decorator.new})
```

So that in the scripts doing:
```lua
decorator(...)
```
Is the same as doing
```lua
decorator.new(...)
```

**Comment by rm-code** [comment]
I don't really see the benefit of doing this ... or is it just for "style" (to mimic the constructor look of other languages)? :smile:

**Comment by Positive07** [comment]
Styles, for sure, just an idea, not a real issue.

**Comment by rm-code** [comment]
I'll give it a try. Do you think I should keep the __new__ function public then or rather force people to use the __construcor__?

**Comment by Positive07** [comment]
Not sure really, I proposed this because new is the only function in the constructor, there is not much you can do with it more than create a new element.

**Comment by rm-code** [comment]
> Not sure really, I proposed this because new is the only function in the constructor, there is not much you can do with it more than create a new element.

True. I didn't see it that way before.
